version: "3.8"

volumes:
  db_data:


services:
  db:
    image: postgres:15
    container_name: chatbot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram-bot
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "src/main.py" ]
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web_server/Dockerfile.web
    container_name: flask-web
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app/web_server
    command: [ "python", "login-server.py" ]
    ports:
      - "5000:5000"
    restart: unless-stopped
