"""Desalojo del constrainst de exclusividad de un chat en el registro general para los usuarios

Revision ID: 0df28de145e1
Revises: a54c8d560ded
Create Date: 2025-06-12 14:22:03.403734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df28de145e1'
down_revision: Union[str, None] = 'a54c8d560ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_telegram_chat_id_key'), 'chat_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('chat_sessions_telegram_chat_id_key'), 'chat_sessions', ['telegram_chat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
