"""Add farms table and selected_farm_id to chat_sessions

Revision ID: 83d48e5b34fe
Revises: 0df28de145e1
Create Date: 2025-06-12 14:38:47.319724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d48e5b34fe'
down_revision: Union[str, None] = '0df28de145e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('litefarm_farm_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('litefarm_farm_id')
    )
    op.add_column('chat_sessions', sa.Column('selected_farm_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'farms', ['selected_farm_id'], ['litefarm_farm_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'selected_farm_id')
    op.drop_table('farms')
    # ### end Alembic commands ###
