"""Initial schema

Revision ID: 99da0196700f
Revises: 
Create Date: 2025-06-06 01:13:28.552324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99da0196700f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_sessions_litefarm_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_telegram_chat_id'), table_name='chat_sessions')
    op.drop_index(op.f('idx_tokens_chat_session_id'), table_name='tokens')
    op.drop_index(op.f('idx_tokens_expires_at'), table_name='tokens')
    op.drop_index(op.f('idx_tokens_token'), table_name='tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tokens_token'), 'tokens', ['token'], unique=False)
    op.create_index(op.f('idx_tokens_expires_at'), 'tokens', ['expires_at'], unique=False)
    op.create_index(op.f('idx_tokens_chat_session_id'), 'tokens', ['chat_session_id'], unique=False)
    op.create_index(op.f('idx_chat_sessions_telegram_chat_id'), 'chat_sessions', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('idx_chat_sessions_litefarm_user_id'), 'chat_sessions', ['litefarm_user_id'], unique=False)
    # ### end Alembic commands ###
