name: Python CI

on:
  push:
    branches: [ main, develop, feature/basic-message-handling, feature/bot-basic-structure ]
  pull_request:
    branches: [ main, develop, feature/basic-message-handling, feature/bot-basic-structure ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Cambia esto si usas otra versión

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dependencies.txt ]; then pip install -r dependencies.txt; fi

        - name: Run tests
      run: pytest

